[package]
name = "binance-history"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.23"
csv = "1.1.6"
rust_decimal = "1.28.1"
reqwest = "0.11.14"
serde = { version = "1.0.152", features = ["derive"] }
serde_with = { version = "2.2.0", features = ["chrono"] }
thiserror = "1.0.38"
tokio = { version = "1.25.0", features = ["full"] }
zip = "0.6.4"
