[package]
name = "binance-data"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.23", features = ["serde"] }
csv = "1.1.6"
rust_decimal = "1.26.1"
reqwest = "0.11.13"
serde = { version = "1.0.148", features = ["derive"] }
thiserror = "1.0.37"
tokio = { version = "1.22.0", features = ["full"] }
zip = "0.6.3"
